# SPDX-License-Identifier: GPL-3.0-or-later
# Copyright (C) 2026 kaede982006
"""Glue between the ML sampler and the existing IO/.gmd writer.

`gmdgen generate --use-ml` ends up here. We sample a list of ExpandedObject
from the trained checkpoint, encode them into the legacy save-string format,
gzip+base64 them into the k4 tag, and write the resulting plist via
:func:`write_gmd_file`.
"""
from __future__ import annotations

import random
from pathlib import Path
from typing import Any

from gmdgen.generate.expand import ExpandedObject
from gmdgen.io.gmd_decoder import encode_level_data, encode_level_description
from gmdgen.io.gmd_writer import write_gmd_file
from gmdgen.ml.sample import generate_from_checkpoint


def _objects_to_save_string(objects: list[ExpandedObject]) -> str:
    """Encode a list of ExpandedObject into Geometry Dash's level data string.

    The format is a header followed by ``;``-separated objects, each a
    comma-separated list of ``key,value`` pairs. Keys 1=id, 2=x, 3=y. We use
    a minimal header so importers do not reject the file.
    """
    header = "kS38,1_40_2_125_3_255_11_255_12_255_13_255_4_-1_6_1000_7_1_15_1_18_0_8_1|"
    header += "kA13,0,kA15,0,kA16,0,kA14,,kA6,0,kA7,0,kA17,0,kA18,0,kS39,0,"
    header += "kA2,0,kA3,0,kA8,0,kA4,0,kA9,0,kA10,0,kA11,0;"
    parts: list[str] = [header]
    for o in objects:
        parts.append(
            f"1,{o.object_id},2,{int(round(o.x))},3,{int(round(o.y))};"
        )
    return "".join(parts)


def run_ml_generate(
    *,
    ckpt_path: Path,
    output: str | None,
    prompt: str,
    sections: int,
    seed: int,
) -> dict[str, Any]:
    if not ckpt_path.exists():
        raise FileNotFoundError(
            f"ML checkpoint not found: {ckpt_path}. Train one with "
            f"`python -m gmdgen.ml.train --in dataset --out {ckpt_path}`."
        )

    # Mix the prompt into the seed deterministically so different prompts
    # produce different samples without changing the model.
    prompt_hash = abs(hash((prompt, seed))) % (2**31 - 1)
    effective_seed = (seed * 1_000_003 + prompt_hash) % (2**31 - 1)

    objects, info = generate_from_checkpoint(
        ckpt_path,
        sections=sections,
        seed=effective_seed,
    )

    save_string = _objects_to_save_string(objects)
    encoded_k4 = encode_level_data(save_string)

    rng = random.Random(effective_seed)
    level_id = str(rng.randint(100_000_000, 999_999_999))
    level_name = (prompt or "AI generated level").strip()[:60] or "AI generated level"
    description = (
        f"Generated by gmdgen v0.1.0 — seed={seed}, sections={sections}\n"
        f"prompt: {prompt[:200]}"
    )

    tags: dict[str, tuple[str, str]] = {
        "kCEK": ("i", "4"),
        "k1": ("i", level_id),
        "k2": ("s", level_name),
        "k3": ("s", encode_level_description(description)),
        "k4": ("s", encoded_k4),
        "k5": ("s", "kaede982006"),
        "k13": ("t", ""),
        "k21": ("i", "2"),
        "k50": ("i", "35"),
    }

    if output:
        out_path = Path(output)
    else:
        Path("outputs").mkdir(exist_ok=True)
        out_path = Path("outputs") / "ml_generated.gmd"
    out_path.parent.mkdir(parents=True, exist_ok=True)
    write_gmd_file(out_path, tags)

    return {
        "ok": True,
        "output": str(out_path),
        "n_objects": info["n_objects"],
        "n_params": info["n_params"],
        "completed_steps": info["completed_steps"],
        "final_eval": info.get("final_eval", {}),
        "level_string_length": len(save_string),
        "encoded_length": len(encoded_k4),
        "seed": seed,
        "effective_seed": effective_seed,
        "sections": sections,
    }


__all__ = ["run_ml_generate"]
